AWSTemplateFormatVersion: 2010-09-09
Description: Sample template for launching Falcon Sensor for Linux container image as an ECS Daemon Service to a cluster
Parameters:
  ECSClusterName:
    Type: String
    Description: Cluster name to deploy Falcon Sensor for Linux as a Daemon Service
  FalconImagePath:
    Type: String
    Description: The ECR image path including tag value for the Falcon Sensor for Linux container image
  SensorMemoryReservation:
    Type: String
    Description: Memory Reservation for the Falcon Sensor
    Default: 128
    AllowedValues:
      - 128

  EnableLogging:
    Type: String
    Description: Boolean string to enable logging for the Falcon ECS service.
    Default: false
    AllowedValues:
      - true
      - false
  EnableExecuteCommand:
    Type: String
    Description: Boolean string to enable ECS exec on the Falcon sensor container. This should be enabled only when required.
    Default: false
    AllowedValues:
      - true
      - false
  ECSExecutionRoleArn:
    Type: String
    Description: Execution role name to exec in to the Falcon container. Only required if ECS exec is enabled.
    Default: ""
  ECSTaskRoleArn:
    Type: String
    Description: Task role name to exec in to the Falcon container. Only required if logging or ECS exec is enabled.
    Default: ""

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Mandatory Fields
        Parameters:
          - ECSClusterName
          - FalconImagePath

Conditions:
  IsLoggingEnabled: !Equals [!Ref EnableLogging, "true"]
  IsExecuteCommandEnabled: !Equals [!Ref EnableExecuteCommand, "true"]
  IsExecutionRoleRequired: !Condition IsExecuteCommandEnabled
  IsTaskRoleRequired: !Or
    - !Condition IsLoggingEnabled
    - !Condition IsExecuteCommandEnabled

Resources:
  FalconECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: cleanup-opt-crowdstrike
          MemoryReservation: 128
          Image: !Ref FalconImagePath
          EntryPoint:
            - "/bin/bash"
          Command:
            - '-c'
            - 'echo "Running /opt/CrowdStrike/falcon-daemonset-init -u"; /opt/CrowdStrike/falcon-daemonset-init -u'
          Essential: false
          Privileged: true
          ReadonlyRootFilesystem: false
          User: 0
          LogConfiguration: !If
            - IsLoggingEnabled
            - LogDriver: awslogs
              Options:
                awslogs-group: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "node-init"
            - !Ref AWS::NoValue
        - Name: cleanup-sleep
          Image: !Ref FalconImagePath
          EntryPoint:
            - "/bin/bash"
          Command:
            - '-c' 
            - 'sleep 300'
          Essential: true
          DependsOn:
            - ContainerName: cleanup-opt-crowdstrike
              Condition: COMPLETE
          MemoryReservation: !Ref SensorMemoryReservation
          Privileged: false
          ReadonlyRootFilesystem: true
          LogConfiguration: !If
            - IsLoggingEnabled
            - LogDriver: awslogs
              Options:
                awslogs-group: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: "node-sensor"
            - !Ref AWS::NoValue
      PidMode: host
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !If
        - IsExecutionRoleRequired
        - !Ref ECSExecutionRoleArn
        - !Ref AWS::NoValue
      TaskRoleArn: !If
        - IsTaskRoleRequired
        - !Ref ECSTaskRoleArn
        - !Ref AWS::NoValue

  FalconECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSClusterName
      SchedulingStrategy: DAEMON
      LaunchType: EC2
      EnableExecuteCommand: !If [IsExecuteCommandEnabled, true, false]
      ServiceName: crowdstrike-falcon-cleanup-daemon
      TaskDefinition: !Ref FalconECSTaskDefinition

  FalconECSServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: IsLoggingEnabled
    Properties:
      LogGroupName: !Sub "/aws/ecs/${ECSClusterName}/crowdstrike/falcon-daemon-service"
